

apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
# frontend - ENABLE_SINGLE_SHARED_SESSION
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: frontend
    spec:
      template:
        spec:
          containers:
            - name: server
              env:
              - name: ENABLE_SINGLE_SHARED_SESSION
                value: "true"
