

apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
# cartservice - replace REDIS_ADDR to target new Memorystore (redis) instance
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: cartservice
    spec:
      template:
        spec:
          containers:
            - name: server
              env:
              - name: REDIS_ADDR
                value: "REDIS_CONNECTION_STRING"
# redis - remove the redis-cart Deployment
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: redis-cart
    $patch: delete
# redis - remove the redis-cart Service
- patch: |-
    apiVersion: v1
    kind: Service
    metadata:
      name: redis-cart
    $patch: delete
